name: Check Website Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Ensure this is up-to-date

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Ensure you are specifying the latest version

    - name: Install dependencies
      run: npm install axios

    - name: Check website status
      run: node check-status.js

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: website-status-results
        path: results.txt
