name: Website Status Check

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read websites from sites.txt
        id: read_sites
        run: |
          sites=$(cat sites.txt)
          echo "::set-output name=sites::$sites"

      - name: Check website statuses
        id: check_status
        run: |
          echo "Website Status Log" > status-log.txt
          IFS=$'\n' # Set newline as delimiter
          for line in ${{ steps.read_sites.outputs.sites }}; do
            url=$(echo $line | cut -d',' -f1)
            title=$(echo $line | cut -d',' -f2)
            response=$(curl -s -o /dev/null -w "%{http_code}" "$url")

            if [ "$response" -eq 200 ]; then
              echo "$title is online (HTTP $response)" >> status-log.txt
            else
              echo "$title is offline (HTTP $response)" >> status-log.txt
            fi
          done

      - name: Commit status log
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add status-log.txt
          git commit -m "Update website status log"
          git push
