name: Check Website Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use a supported Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run website status check
        run: |
          # Create a JavaScript file to check website status
          echo "
          const fs = require('fs');
          const axios = require('axios');

          async function checkWebsiteStatus() {
              const sites = fs.readFileSync('sites.txt', 'utf-8').split('\\n');
              for (const site of sites) {
                  const [url, title] = site.split(',');
                  if (url && title) {
                      try {
                          const response = await axios.get(url.trim());
                          console.log(\`Website: \${title.trim()} - Status: \${response.status}\`);
                      } catch (error) {
                          console.log(\`Website: \${title.trim()} - Status: Offline\`);
                      }
                  }
              }
          }

          checkWebsiteStatus();
          " > check-status.js

          # Run the JavaScript file
          node check-status.js
